### ISSUE TITLE
Support DB_NAME in the database link

### ISSUE THREAD

**Issue by quentinguidee** [vertex-center/vertex#12]
Currently, we can select a database to link it to an instance. However, it is not possible to select the database (`DB_NAME`).

One way of supporting that in the "Vertex Containers" app should be to add a field to enter the database name. Later, the SQL app will also manage the creation of this database.

<img width="1600" alt="image" src="https://github.com/vertex-center/vertex/assets/12123721/9dd03304-3736-40f4-9655-370265b341e4">

**Comment by MinhDuongg** [comment]
I'd like to contribute to this feature

**Comment by Syycorax** [comment]
Hello, thanks for offering your help.
I suggest taking a look at [the contributor's guide](https://vertex.quentinguidee.dev/docs/docs/contribute/code-contributions/vertex). Don't hesitate to join [our discord](https://discord.gg/tGZV6X6ZJh) if you need help with anything!

**Comment by quentinguidee** [comment]
Thanks! I added some details to the issue; as @Syycorax said don't hesitate if you have any questions!

**Comment by MinhDuongg** [comment]
yeah, I'm still working on it. However, I have some issues with the frontend cause I'm not familiar with React :(
