### ISSUE TITLE
Customize Vertex name and logo

### ISSUE THREAD

**Issue by quentinguidee** [vertex-center/vertex#5]
Should be good to add a new administration setting to change the logo and name of Vertex

**Comment by Overengined** [comment]
I don't think it  really is a good idea. The logo and the name create an easily recogniseable image for vertex. If people can change the logo and/or the name, you loose that sort of "brand image".

**Comment by Bzyli** [comment]
> I don't think it really is a good idea. The logo and the name create an easily recogniseable image for vertex. If people can change the logo and/or the name, you loose that sort of "brand image".
I agree, maybe you should just add some customization options to the UI (color scheme, custom banner as in Portainer)

**Comment by Overengined** [comment]
> > I don't think it really is a good idea. The logo and the name create an easily recogniseable image for vertex. If people can change the logo and/or the name, you loose that sort of "brand image".
> 
> I agree, maybe you should just add some customization options to the UI (color scheme, custom banner as in Portainer)
> 

Why not change the color of the logo? Its a nice compromise between changing everything and nothing.

**Comment by quentinguidee** [comment]
Closing as not planned. The default theme is done with the red logo in mind, so other colours will probably break the design.
