### ISSUE TITLE
Empty route in the reverse proxy

### ISSUE THREAD

**Issue by quentinguidee** [vertex-center/vertex#54]
It is possible to create empty proxy redirection (source = "" and/or host = ""), which the proxy service should not allow.

**Comment by AshwinKul28** [comment]
Hello, @quentinguidee I can take this issue.

**Comment by Syycorax** [comment]
Hello, thanks for offering your help.
I suggest taking a look at [the contributor's guide](https://vertex.quentinguidee.dev/docs/docs/contribute/code-contributions/vertex). Don't hesitate to join [our discord](https://discord.gg/tGZV6X6ZJh) if you need help with anything!

**Comment by quentinguidee** [comment]
Solved with #85
